version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: aviazo
      WORDPRESS_DB_PASSWORD: Aa123456
      WORDPRESS_DB_NAME: wordpressdb
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: aviazo
      MYSQL_PASSWORD: Aa123456
